# _config.yml
source: .


exclude:
  - assets/css/style.scss
  - assets/scss


# Pengaturan dasar
title: "https://github.com/venivansur"
description: "Deskripsi singkat tentang situs ini."
baseurl: "" 
url: "https://github.com/venivansur/venivansurya"  # Ganti dengan URL situs Anda, misalnya "https://username.github.io"

# Direktori sumber dan hasil build
source: "docs"  # Menentukan folder sumber, jika Anda menggunakan folder 'docs'
destination: "_site"  # Folder untuk hasil build

# Pengaturan untuk Jekyll SEO Tag
plugins:
  - jekyll-seo-tag

# Mengaktifkan dukungan untuk Markdown
markdown: kramdown  # Gunakan kramdown sebagai parser Markdown

# Pengaturan timezone dan format tanggal
timezone: "Asia/Jakarta"  # Ganti dengan timezone Anda
date_format: "%Y-%m-%d"  # Format tanggal yang digunakan dalam posts

# Menyertakan direktori dan file
include:
  - "_posts"   # Menyertakan folder _posts untuk posting blog
  - "_includes"  # Menyertakan folder _includes untuk file partials
  - "_layouts"  # Menyertakan folder _layouts untuk file layout

# Mengaktifkan RSS feed
plugins:
  - jekyll-feed

# Menambahkan baseurl jika proyek ada di subdirektori
baseurl: "/projekku"

# Set apakah build incremental diaktifkan (gunakan ini untuk build lebih cepat)
incremental: false
